# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9078610309d9824a8f802d9a18ae8852b99b3246610cda1ba0d9306e2d43bcb5563173d4f8231041ffea18056abf12d644d6db68f2af3d3d24f45cd2463cf87c

test:
  secret_key_base: 4afe8abb38bf6e3903e12f0f3e943bd4df589fbc5f0c005ac4ceea805d7639694b939c5a20208b44d48b363a37b3d91ce1a09f5d3c0bfee04fe660884eed8158

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
